baseURL = "http://localhost:1313"
canonifyURLs = false
relativeURLs = false
languageCode = "en-us"
title = "Data Explorer"
enableRobotsTXT = true
metaDataFormat = "yaml"
theme = "dohmh"
publishDir = "docs"
paginate = 9
ignoreFiles = ['Simplified.Chinese', 'Spanish']
# enableGitInfo = true

[caches]
    [caches.getresource]
      dir = ':cacheDir/:project'
      maxAge = -1

[imaging]
  anchor = 'Smart'
  bgColor = '#ffffff'
  hint = 'photo'
  quality = 95
  resampleFilter = 'MitchellNetravali'

[markup.goldmark.parser]
  autoHeadingID = false # remove md headings from pagefind results

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup.goldmark.parser.attribute]
  block = false
  title = true # allow apending attributes to md headings

[module]

  [[module.mounts]]
    source = "node_modules"
    target = "assets/node_modules"

 [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "layouts"
    target = "layouts"

  [[module.mounts]]
    source = "data"
    target = "data"

  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "i18n"
    target = "i18n"

  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"